Ask if the user really wants to pastebin
Akuli/porcupine pull request #1054
Opened 2022-04-12 13:34 UTC by Akuli

Fixes #1027

2022-04-12 13:45 UTC, Akuli commented on tests/test_pastebin_plugin.py
> +    mock_run.return_value = "https://foobar"
```suggestion
```

2022-04-15 21:12 UTC, Akuli commented
@rdbende Can you review this? I added some padding to the labels, but I probably missed something else :)

2022-04-15 21:37 UTC, rdbende requested changes

2022-04-15 21:37 UTC, rdbende commented on porcupine/plugins/pastebin.py
> +    window = tkinter.Toplevel()
```suggestion
    window = tkinter.Toplevel()
    window.transient(get_main_window())
```
Just so it doesn't appear as a separate icon on my taskbar ;)

2022-04-15 21:37 UTC, rdbende commented on porcupine/plugins/pastebin.py
> +    ttk.Button(button_frame, text="No", command=no).pack(side="left", expand=True)
```suggestion
    ttk.Button(button_frame, text="Yes", command=yes).pack(side="left", expand=True, fill="x", padx=(0, 10))
    ttk.Button(button_frame, text="No", command=no).pack(side="left", expand=True, fill="x", padx=(10, 0))
```
bigger clickable area

2022-04-15 21:37 UTC, rdbende commented on porcupine/plugins/pastebin.py
> +        text=f"Do you want to send the content of {filename} to {paste_class.name}?",
This text can be misleading, it says, `the content of {filename}` even if I just try to pastebin the selection.

2022-04-15 22:51 UTC, Akuli commented
Thanks for the review!

2022-04-18 13:59 UTC, merged