Undo ctrl + f through change_batch
Akuli/porcupine pull request #476
Opened 2021-06-06 22:21 UTC by ThePhilgrim

Fixes #431

2021-06-06 22:24 UTC, Akuli reviewed
Looks good overall! A couple small nits.

2021-06-06 22:24 UTC, Akuli commented on tests/test_find_plugin.py
> +    finder.show()
Nit: There's no need to hide it. You can just leave it shown for the whole time.

2021-06-06 22:24 UTC, Akuli commented on tests/test_find_plugin.py
> +    finder.replace_all_button.invoke()
Can you also add a test for "Replace this" button?

2021-06-06 22:29 UTC, Akuli requested changes

2021-06-06 22:29 UTC, Akuli commented on tests/test_find_plugin.py
> +    filetab.textwidget.tag_add("sel", "1.0", "1.3")
```suggestion
    filetab.textwidget.tag_add("sel", "1.0", "1.3")  # Select foo so it goes to find entry
```

2021-06-06 22:31 UTC, Akuli commented on tests/test_find_plugin.py
> +    finder.replace_all_button.invoke()
...or add to end of this test, whatever feels better :)

2021-06-06 23:31 UTC, ThePhilgrim commented
**Found bug that needs addressing!**

If you find text so it's highlighted, and you replace it, then ctrl + f, the text is no longer highlighted. This can become problematic if you want to replace something, then ctrl + f cause you realize you want to replace all. Then all wont be replaced.

I spend time trying to fix it, but I can't figure out how I would do it. My thought was to add a trace or Event to tkinter's edit_undo(). If the event runs, and find window is open -> run highlight_text(). I can't find how to trace the undo event.. Seems impossible.


https://imgur.com/bk01kf2

2021-06-07 09:19 UTC, Akuli commented
I think this problem only happens when you undo a "Replace this" operation, as there is no other way to get a match that isn't highlighted. And if you undo "Replace this", it means you didn't want that match to get replaced, so it should behave just like clicking "Next match". The difference is that the "Next match" button leaves it highlighted, so that "Replace all" will find it.

I can see a few options:
- Trace the undo event. When undoing a "Replace this" operation, it would re-highlight the match. I can see one way to trace an undo event, but I think it would be difficult to figure out whether it was a "Replace this" undo or some other undo. It's important to get that right, because we really don't want to touch other unrelated undos. I see this as a limitation in Tk's undo mechanism, and we can revisit this if I ever make custom undo logic.
- Ignore highlights in "Replace all". This becomes a problem if you first find something, then add more matches by editing the text, and then "Replace all", as it will also replace the new matches **without ever highlighting them**. That's surprising, and I don't want that.
- Do nothing. This seems fine to me.

I would prefer this to be fixed in a separate PR. You can still leave the failing test in and mark it with [pytest.mark.xfail](https://docs.pytest.org/en/reorganize-docs/new-docs/user/xfail.html). I would prefer two separate tests, one succeeding test for the functionality that this PR adds (that you had earlier) and another xfail test for the new bug.

2021-06-07 09:27 UTC, ThePhilgrim commented
Actually, I can see this happening though. Not often. But I sometimes replace, change my mind, and then change my mind again (redo the undo)

If it possible to trace the undo event (I found no way to do it), I would on the undo event, check if finder window is open, and if so, run the highlight text method. That means that:

1) if finder is not open, nothing happens
2) if finder is open, but no text is in find entry, nothing will be highlighted,
3) if finder is open and find entry contains something, it will highlight that text again. Which is the expected behaviour.

So if there is a way to get a trace undo, it should be a simple fix.

2021-06-07 09:27 UTC, ThePhilgrim commented
> I would prefer this to be fixed in a separate PR. You can still leave the failing test in and mark it with [pytest.mark.xfail](https://docs.pytest.org/en/reorganize-docs/new-docs/user/xfail.html). I would prefer two separate tests, one succeeding test for the functionality that this PR adds (that you had earlier) and another xfail test for the new bug.

Okay, will split them up tonight after work

2021-06-07 09:42 UTC, Akuli commented
There is an event named `<<Undo>>` which runs on Ctrl+Z press, but not when the `.edit_undo()` method is called. It seems good enough for me.

To use it in the find plugin, you would write:

```
def __init__(self, whatever):
    ...
    self._textwidget.bind("<<Undo>>", self._handle_undo, add=True)
    ...

def _handle_undo(self, event: object) -> None:
    ...
```

As you would expect, `event` is something that tkinter passes the the callback function, but we don't need in this case.

You will need to change the test to use `filetab.textwidget.event_generate("<<Undo>>")` instead of `filetab.textwidget.edit_undo()` to better simulate the user pressing Ctrl+Z, as the `<<Undo>>` event doesn't catch `.edit_undo()`. If the undo event doesn't seem to work in the test, you can add `filetab.update()` before it.

Alternatively, we can add more code under the big warning triangle comment in porcupine/textwidget.py. That magic is powerful enough to catch all undos, including those created with the `.edit_undo()` method.

2021-06-07 09:46 UTC, Akuli commented
Turns out there's one more gotcha with the `<<Undo>>` event: it runs before the undoing actually happens, and if the undo changes `bar` to `foo`, the bind callback will see `bar`. To work around this, you can use `after_idle`, which runs a function later, when the event loop is done with processing the `<<Undo>>`:

```python
def _handle_undo(self, event: object) -> None:
    self.after_idle(self.highlight_all_matches)
```

2021-06-07 18:39 UTC, Akuli commented on tests/test_find_plugin.py
> +def replace_this_greyed_out(filetab_and_finder):
```suggestion
def test_replace_this_greyed_out(filetab_and_finder):
```

2021-06-07 18:53 UTC, Akuli approved these changes

2021-06-07 18:54 UTC, merged